config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'home#index'

  resources :accounts, only: [:show, :create, :update]

  resources :account_subscriptions, only: [:show, :update]

  resources :users do
    resources :todos
  end
  post '/users_create' => 'users#create'

  resources :inquired_users, only: [:index, :update]

  resources :available_days

  resources :levels do
    resources :level_memberships, only: [:create, :destroy, :update]
  end

  resources :pricing_plans do
    resources :plan_enrollments, only: [:new, :create, :destroy, :update]
  end

  resources :rooms

  resources :roles

  resources :users_roles, only: [:create, :destroy]

  resources :housings do
    resources :housing_occupancies, only: [:create, :destroy, :update]
  end

  resources :events do
    resources :event_sessions
    resources :event_attendances
  end

  resources :event_sessions do
    resources :event_attendances
  end

  resources :class_schedules

  resources :start_end_times

  resources :payments

  resources :payment_items

  namespace :payments do
    resources :payment_items, only: :destroy
  end
  get 'export_payments' => 'payments/csv_exporters#index', default: { format: :csv }

  resources :integrations

  resources :integration_processors, only: :create

  resources :report_teachers, only: :index

  resources :registration_forms, only: [:show, :update]

  namespace :registration_forms do
    resources :student_registrations, only: [:new, :create]
  end

  resources :terms_of_services

  resources :user_initial_setup, only: :index

  namespace :user_initial_setup do
    resources :assign_user_to_accounts, only: :create
  end

  # Integration sample files downloads routes
  get 'integration_user_csv' => 'integrations_sample_file_downloads#download_user_csv'
  get 'integration_housing_csv' => 'integrations_sample_file_downloads#download_housing_csv'
  get 'integration_housing_occupancy_csv' => 'integrations_sample_file_downloads#download_housing_occupancy_csv'
  get 'integration_plan_enrollment_csv' => 'integrations_sample_file_downloads#download_plan_enrollment_csv'

  namespace :ui, defaults: { format: 'json' } do
    namespace :v1 do
      resources :rooms, only: :index
      resources :students, only: :index
      resources :teachers, only: :index
      resources :class_sessions, only: %i(create show update destroy)
      resources :schedule_exports, only: :create

      resources :todos, only: %i(create index) do
        patch :update, on: :collection
      end
    end
  end

  # Stripe subscription actions
  post 'subscribe' => 'stripe_subscriptions#subscribe'
  post 'resume_subscription' => 'stripe_subscriptions#resume_subscription'
  post 'pause_subscription' => 'stripe_subscriptions#pause_subscription'
  post 'add_a_new_card' => 'stripe_subscriptions#add_a_new_card'
  delete 'delete_card' => 'stripe_subscriptions#delete_card'
  put 'make_default_card' => 'stripe_subscriptions#make_default_card'
end

app/models/pricing_plan.rb
class PricingPlan < ApplicationRecord
  include Codeable

  has_many :plan_enrollments, dependent: :destroy
  has_many :users, through: :plan_enrollments
  has_many :start_end_times, as: :timeable, dependent: :destroy
  has_many :registration_informations, dependent: :destroy
  has_one :note, as: :noteable, dependent: :destroy
  belongs_to :account

  FREQUENCY_PLANS = %w(hour day week)

  validates :account, presence: true
  validates :name, presence: true
  validates :frequency,
            presence: true,
            numericality: { only_integer: true, greater_than: 0 }
  validates :frequency_unit,
            presence: true,
            inclusion: { in: FREQUENCY_PLANS }
  validates :code, uniqueness: { scope: :account_id }

  monetize :price_cents,
           allow_nil: false,
           with_model_currency: :currency

  after_save :set_code_if_blank, if: Proc.new { |pp| pp.code.blank? }

  accepts_nested_attributes_for :note

  scope :private_plans, -> { where(private_plan: true) }
  scope :group_plans, -> { where(private_plan: false) }


  def self.currency_collection
    Money::Currency.table.collect do |currency|
      ["#{currency.last[:name]} (#{currency.last[:iso_code]})",
       currency.last[:iso_code]]
    end
  end

  def self.frequency_plan_collection
    FREQUENCY_PLANS.collect { |plan| [plan.capitalize, plan] }
  end

  def active_users
    account.users.where(id: plan_enrollments.active.pluck(:user_id))
  end

  def inactive_users
    account.users.where(id: plan_enrollments.inactive.pluck(:user_id))
  end
end

app/controllers/pricing_plans_controller.rb
class PricingPlansController < ApplicationController
  before_action :authenticate_user!
  before_action :find_pricing_plan, only: [:edit, :show, :update, :destroy]

  def index
    @pricing_plans = policy_scope(PricingPlan)
  end

  def new
    @pricing_plan = PricingPlan.new(account: current_account)
    @pricing_plan.build_note
    authorize @pricing_plan
  end

  def edit
    authorize @pricing_plan
  end

  def show
    authorize @pricing_plan
  end

  def create
    @pricing_plan = PricingPlan.new(pricing_plan_params.merge(account: current_account))
    @pricing_plan.build_note if @pricing_plan.note.nil?
    authorize @pricing_plan
    @pricing_plan.price_currency = current_account.currency
    @pricing_plan.currency = current_account.currency
    @pricing_plan.price = if pricing_plan_params[:price_cents].try { |pc| pc.include?('.') }
                            pricing_plan_params[:price_cents].try(:to_f)
                          else
                            pricing_plan_params[:price_cents].try(:to_i)
                          end
    @pricing_plan.note.noteable = @pricing_plan

    if @pricing_plan.save
      flash[:success] = I18n.t('pricing_plan_successfully_created')
      redirect_to @pricing_plan
    else
      flash[:error] = I18n.t('something_went_wrong')
      render :new
    end
  end

  def update
    authorize @pricing_plan
    @pricing_plan.assign_attributes(pricing_plan_params)
    @pricing_plan.price_currency = current_account.currency
    @pricing_plan.currency = current_account.currency
    @pricing_plan.price = if pricing_plan_params[:price_cents].try { |pc| pc.include?('.') }
                            pricing_plan_params[:price_cents].try(:to_f)
                          else
                            pricing_plan_params[:price_cents].try(:to_i)
                          end

    if @pricing_plan.save
      flash[:success] = I18n.t('pricing_plan_successfully_updated')
      redirect_to @pricing_plan
    else
      flash[:error] = I18n.t('something_went_wrong')
      render :edit
    end
  end

  def destroy
    authorize @pricing_plan
    @pricing_plan.destroy
    flash[:success] = I18n.t('pricing_plan_successfully_deleted')
    redirect_to pricing_plans_path
  end

  private

  def pricing_plan_params
    params.require(:pricing_plan).permit(:name, :price_cents, :frequency,
      :frequency_unit, :private_plan, :hours_per_week, :hours_per_day,
      note_attributes: [:id, :noteable, :noteable_id, :noteable_type, :body])
  end

  def find_pricing_plan
    @pricing_plan = current_account.pricing_plans.find(params[:id])
  end
end

app/views/pricing_plans/_form.html.erb
<%= form_for pricing_plan, html: { class: 'cmxform form-horizontal tasi-form' } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :code, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :code, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price_cents, "#{t('price')} - #{account.currency}", class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :price_cents, value: pricing_plan.price.to_s, step: 0.01, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :frequency, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :frequency, min: 1, step: 1, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :frequency_unit, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :frequency_unit, PricingPlan.frequency_plan_collection, {}, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :hours_per_week, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :hours_per_week, min: 0, step: 1, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :hours_per_day, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :hours_per_day, min: 0, step: 1, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :private_plan, class: 'control-label col-lg-2' %>
    <div class="col-lg-10 control-label">
      <%= f.check_box :private_plan, class: 'hidden' %>
      <div id="pricing-plan-private-plan-toggle" class="toggle toggle-success"></div>
    </div>
  </div>

  <div class="form-group">
    <%= f.fields_for :note do |n| %>
      <%= n.label :note, t('notes'), class: 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= n.text_area :body, class: 'form-control' %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit t('save'), class: 'btn btn-success' %>
      <%= link_to t('cancel'), :back, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/pricing_plans/_pricing_plan.html.erb
<%= link_to pricing_plan_path(pricing_plan) do %>
  <div class="col-lg-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pricing_plan.name %></h3>
      </div>
      <div class="panel-body">
        <p><%= simple_format(pricing_plan.note.try(:body)) || 'N/A' %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/pricing_plans/edit.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= t('edit_pricing_plan') %></h3>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @pricing_plan.name %></h3>
        </div>
        <div class="panel-body">
          <div class="form">
            <%= render partial: 'form', locals: { pricing_plan: @pricing_plan, account: current_account } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pricing_plans/index.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= t('pricing_plans') %></h3>
  </div>

  <% @pricing_plans.in_groups_of(3).each do |grouped_pricing_plans| %>
    <div class="row">
      <% grouped_pricing_plans.compact.each do |pricing_plan| %>
        <%= render pricing_plan %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pricing_plans/new.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= t('new_pricing_plan') %></h3>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t('new_pricing_plan') %></h3>
        </div>
        <div class="panel-body">
          <div class="form">
            <%= render partial: 'form', locals: { pricing_plan: @pricing_plan, account: current_account } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pricing_plans/show.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= @pricing_plan.name %></h3>
  </div>

  <div class="row">
    <div class="col-md-12">
      <ul class="list-inline">
        <li><%= link_to t('edit'), edit_pricing_plan_path(@pricing_plan), class: 'btn btn-info'  %></li>
        <li><%= link_to t('delete'), pricing_plan_path(@pricing_plan), method: :delete, class: 'btn btn-danger', data: { confirm: t('are_you_sure') } %></li>
      </ul>
      <br>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-sm-6 col-md-3">
      <div class="panel">
        <div class="h2 text-purple"><%= humanized_money_with_symbol @pricing_plan.price %></div>
        <span class="text-muted"><%= t('price') %></span>
        <div class="text-right">
          <i class="fa fa-usd fa-2x text-purple"></i>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-3">
      <div class="panel bg-primary">
        <div class="h2 text-white"><%= @pricing_plan.frequency %> <%= "#{@pricing_plan.frequency_unit}#{'s' if @pricing_plan.frequency > 1}" %></div>
        <span class="text-white"><%= t('frequency') %></span>
        <div class="text-right">
          <i class="fa fa-calendar fa-2x text-white"></i>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-3">
      <div class="panel">
        <div class="h2 text-primary"><%= @pricing_plan.active_users.count %></div>
        <span class="text-muted"><%= t('current_students') %></span>
        <div class="text-right">
          <i class="fa fa-user fa-2x text-primary"></i>
        </div>
      </div>
    </div>
  </div>

  <div class="page-title">
    <h3 class="title"><%= t('plan_schedules') %></h3>
  </div>

  <div class="row">
    <div class="col-md-12">
      <ul class="list-inline">
        <li><%= link_to t('add_schedule'), new_start_end_time_path(timeable_type: @pricing_plan.class.name, timeable_id: @pricing_plan.id), class: 'btn btn-info'  %></li>
      </ul>
      <br>
    </div>
  </div>

  <% if @pricing_plan.start_end_times.any? %>
    <ul class="list-group">
      <% @pricing_plan.start_end_times.each do |schedule| %>
        <li class="list-group-item">
          <%= "#{schedule.start_on.in_time_zone(current_account.time_zone).strftime('%l:%M %p').strip} - #{schedule.end_on.in_time_zone(current_account.time_zone).strftime('%l:%M %p').strip}" %>
          <%= link_to t('delete'), start_end_time_path(schedule, timeable_type: @pricing_plan.class.name, timeable_id: @pricing_plan.id), method: :delete, data: { confirm: t('are_you_sure') }, class: 'btn btn-danger badge' %>
          <%= link_to t('edit'), edit_start_end_time_path(schedule, timeable_type: @pricing_plan.class.name, timeable_id: @pricing_plan.id), class: 'btn btn-info badge' %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <div class="alert alert-warning">
      <%= I18n.t('you_do_not_have_any_schedules_for_this_pricing_plan') %>
    </div>
  <% end %>

  <div class="page-title">
    <h3 class="title"><%= t('enrolled_students') %></h3>
  </div>

  <div class="row">
    <div class="col-md-12">
      <ul class="list-inline">
        <li><%= link_to t('enroll_a_user'), 'javascript:;', class: 'md-trigger btn btn-info', data: { modal: 'new-plan-enrollment-modal'} %></li>
      </ul>
      <br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <ul class="nav nav-tabs">
        <li class="active">
          <a href="#active-students" data-toggle="tab" aria-expanded="false">
            <span class="visible-xs"><%= t('active')%></span>
            <span class="hidden-xs"><%= t('active') %></span>
          </a>
        </li>
        <li>
          <a href="#inactive-students" data-toggle="tab" aria-expanded="true">
            <span class="visible-xs"><%= t('inactive') %></span>
            <span class="hidden-xs"><%= t('inactive') %></span>
          </a>
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="active-students">
          <ul class="list-group list-group-lg">
            <% plan_enrollments = @pricing_plan.plan_enrollments %> <% active_plan_enrollments = plan_enrollments.active.includes(:user) %>
            <% active_plan_enrollments.each do |plan_enrollment| %>
              <li class="list-group-item b-0">
                <% user = plan_enrollment.user %>
                <% link_path =  pricing_plan_plan_enrollment_path(@pricing_plan, plan_enrollment, plan_enrollment: { active: false }) %>
                <%= link_to user_path(user), class: 'm-r-10' do %>
                  <%= image_tag user.avatar.url(:thumb), class: 'thumb-sm br-radius' %>
                <% end %>
                <%= link_to link_path, method: :delete do %>
                  <span class="pull-right label bg-danger inline m-t-10"><%= t('delete') %></span>
                <% end %>
                <%= link_to "#{user.full_name} (#{plan_enrollment.start_end_time.start_on.strftime('%m/%d/%Y')} - #{plan_enrollment.start_end_time.end_on.strftime('%m/%d/%Y')})", user_path(user) %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="tab-pane" id="inactive-students">
          <ul class="list-group list-group-lg">
            <% inactive_plan_enrollments = plan_enrollments.inactive.includes(:user) %>
            <% inactive_plan_enrollments.each do |plan_enrollment| %>
              <li class="list-group-item b-0">
                <% user = plan_enrollment.user %>
                <%= link_to user_path(user), class: 'm-r-10' do %>
                  <%= image_tag user.avatar.url(:thumb), class: 'thumb-sm br-radius' %>
                <% end %>
                <%= link_to "#{user.full_name} (#{plan_enrollment.start_end_time.start_on.strftime('%m/%d/%Y')} - #{plan_enrollment.start_end_time.end_on.strftime('%m/%d/%Y')})", user_path(user) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="md-modal md-effect-16" id="new-plan-enrollment-modal">
  <% new_plan_enrollment = @pricing_plan.plan_enrollments.build %>
  <% new_plan_enrollment.build_start_end_time %>
  <%= form_for [@pricing_plan, new_plan_enrollment], html: { class: 'form-horizontal' } do |f| %>
    <div class="md-content">
      <h3><%= t('enroll_a_user') %></h3>

      <div class="form-group">
        <%= f.label :user_id, class: 'col-sm-3 control-label' %>
        <div class="col-sm-9">
          <%= f.select :user_id, current_account.students_collection(@pricing_plan.users), {}, class: 'form-control' %>
        </div>
      </div>

      <%= f.fields_for :start_end_time do |s| %>
        <% start_end_time = new_plan_enrollment.start_end_time %>
        <div class="form-group">
          <label class="control-label col-lg-3"><%= I18n.t('start_on') %></label>
          <div class="col-lg-9">
            <%= s.date_field :start_date,
                value: start_end_time.start_on.try { |date| date.in_time_zone(current_account.time_zone).strftime('%-m/%-d/%Y').strip },
                class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <label class="control-label col-lg-3"><%= I18n.t('end_on') %></label>
          <div class="col-lg-9">
            <%= s.date_field :end_date,
                value: start_end_time.end_on.try { |date| date.in_time_zone(current_account.time_zone).strftime('%-m/%-d/%Y').strip },
                class: 'form-control' %>
          </div>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :price_cents, "#{t('price')} - #{current_account.currency}", class: 'control-label col-lg-3' %>
        <div class="col-lg-9">
          <%= f.number_field :price_cents, value: new_plan_enrollment.price.to_s, step: 0.01, class: 'form-control' %>
          <span><%= t('cost') %> - <%= humanized_money_with_symbol(@pricing_plan.price) %> / <%= "#{@pricing_plan.frequency} #{@pricing_plan.frequency_unit}" %></span><br>
        </div>
      </div>

      <div class="form-group m-b-0">
        <div class="col-sm-offset-4 col-sm-8">
          <%= link_to t('cancel'), 'javascript:;', class: 'md-close btn btn-default btn-sm' %>
          <%= f.submit t('submit'), class: 'btn-sm btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="md-overlay"></div>