config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'home#index'

  resources :accounts, only: [:show, :create, :update]

  resources :account_subscriptions, only: [:show, :update]

  resources :users do
    resources :todos
  end
  post '/users_create' => 'users#create'

  resources :inquired_users, only: [:index, :update]

  resources :available_days

  resources :levels do
    resources :level_memberships, only: [:create, :destroy, :update]
  end

  resources :pricing_plans do
    resources :plan_enrollments, only: [:new, :create, :destroy, :update]
  end

  resources :rooms

  resources :roles

  resources :users_roles, only: [:create, :destroy]

  resources :housings do
    resources :housing_occupancies, only: [:create, :destroy, :update]
  end

  resources :events do
    resources :event_sessions
    resources :event_attendances
  end

  resources :event_sessions do
    resources :event_attendances
  end

  resources :class_schedules

  resources :start_end_times

  resources :payments

  resources :payment_items

  namespace :payments do
    resources :payment_items, only: :destroy
  end
  get 'export_payments' => 'payments/csv_exporters#index', default: { format: :csv }

  resources :integrations

  resources :integration_processors, only: :create

  resources :report_teachers, only: :index

  resources :registration_forms, only: [:show, :update]

  namespace :registration_forms do
    resources :student_registrations, only: [:new, :create]
  end

  resources :terms_of_services

  resources :user_initial_setup, only: :index

  namespace :user_initial_setup do
    resources :assign_user_to_accounts, only: :create
  end

  # Integration sample files downloads routes
  get 'integration_user_csv' => 'integrations_sample_file_downloads#download_user_csv'
  get 'integration_housing_csv' => 'integrations_sample_file_downloads#download_housing_csv'
  get 'integration_housing_occupancy_csv' => 'integrations_sample_file_downloads#download_housing_occupancy_csv'
  get 'integration_plan_enrollment_csv' => 'integrations_sample_file_downloads#download_plan_enrollment_csv'

  namespace :ui, defaults: { format: 'json' } do
    namespace :v1 do
      resources :rooms, only: :index
      resources :students, only: :index
      resources :teachers, only: :index
      resources :class_sessions, only: %i(create show update destroy)
      resources :schedule_exports, only: :create

      resources :todos, only: %i(create index) do
        patch :update, on: :collection
      end
    end
  end

  # Stripe subscription actions
  post 'subscribe' => 'stripe_subscriptions#subscribe'
  post 'resume_subscription' => 'stripe_subscriptions#resume_subscription'
  post 'pause_subscription' => 'stripe_subscriptions#pause_subscription'
  post 'add_a_new_card' => 'stripe_subscriptions#add_a_new_card'
  delete 'delete_card' => 'stripe_subscriptions#delete_card'
  put 'make_default_card' => 'stripe_subscriptions#make_default_card'
end

app/models/payment.rb
class Payment < ApplicationRecord
  has_paper_trail

  PAYMENT_METHODS = %w(cash credit debit paypal)

  has_many :payment_items, dependent: :destroy
  belongs_to :account
  belongs_to :user

  validates :account, presence: true
  validates :user, presence: true
  validates :due_on, presence: true
  validates :payment_method, inclusion: { in: PAYMENT_METHODS }, allow_nil: true
  validates :paid_on, presence: true, if: :paid

  monetize :subtotal_cents,
           allow_nil: false,
           with_model_currency: :currency

  monetize :total_cents,
           allow_nil: false,
           with_model_currency: :currency

  before_save :set_discount, :set_total
  after_update :update_payment_items_to_paid,
               if: Proc.new { |payment| payment.changed? && payment.paid? }

  scope :overdue, -> { where('due_on < ?', Date.today) }

  def self.payment_methods_collection
    PAYMENT_METHODS.collect { |payment_method| [payment_method.capitalize, payment_method] }
  end

  def set_subtotal!
    self.subtotal = payment_items.map(&:price).sum
    self.save
  end

  def discount_to_number
    self.discount * 100
  end

  def payable_by_student?
    account.country == 'USA'
  end

  def payment_status
    paid? ? I18n.t('paid') : I18n.t('pending')
  end

  private

  def set_discount
    self.discount = 0.0 and return if self.discount.nil?
    self.discount /= 100 and return if self.discount > 1
  end

  def set_total
    self.total = self.subtotal - (self.subtotal * self.discount)
  end

  def update_payment_items_to_paid
    payment_items.update_all(paid: true, paid_on: paid_on)
  end
end

app/controllers/payments/csv_exporters_controller.rb
class Payments::CsvExportersController < ApplicationController
  before_action :authenticate_user!

  def index
    authorize current_account, :update?

    start_date = params[:start_date].to_date
    end_date = params[:end_date].to_date

    respond_to do |format|
      format.csv do
        send_data PaymentsReportExportService.new(current_account, start_date, end_date).process!, filename: "payments-#{Date.today}.csv"
      end
    end
  end
end

app/controllers/payments/payment_items_controller.rb
class Payments::PaymentItemsController < ApplicationController
  before_action :authenticate_user!

  def destroy
    @payment_item = current_account.payment_items.find(params[:id])
    authorize @payment_item, :update?
    @payment      = @payment_item.payment
    @payment_item.update_attributes(payment: nil)
    @payment.set_subtotal!
    redirect_to payment_path(@payment)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_payment, only: [:show, :edit, :update]

  def index
    @payments = policy_scope(Payment)
    @payments = @payments.includes(:user)
  end

  def show
    authorize @payment
    @payment_items = @payment.payment_items.includes(:itemable)
  end

  def edit
    authorize @payment
  end

  def update
    authorize @payment

    if @payment.update_attributes(payment_params)
      flash[:success] = I18n.t('payment_successfully_updated')
      redirect_to @payment
    else
      flash[:error] = I18n.t('something_went_wrong')
      render :show
    end
  end

  private

  def find_payment
    @payment = current_account.payments.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:paid, :due_on, :discount,
      :payment_method, :paid_on)
  end
end

app/views/payments/edit.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= t('edit_payment') %></h3>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t('invoice_for') %>: <%= @payment.user.full_name %></h3>
        </div>
        <div class="panel-body">
          <div class="form">
            <%= form_for @payment, html: { class: 'cmxform form-horizontal tasi-form' } do |f| %>
              <div class="form-group">
                <%= f.label :discount, class: 'control-label col-lg-2' %>
                <div class="col-lg-10">
                  <%= f.number_field :discount, max: 100, step: 0.01, class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :due_on, class: 'control-label col-lg-2' %>
                <div class="col-lg-10">
                  <%= f.date_field :due_on, class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                  <%= f.submit t('save'), class: 'btn btn-success' %>
                  <%= link_to t('cancel'), :back, class: 'btn btn-default' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/payments/index.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= t('payments') %></h3>
  </div>

  <div class="row">
    <div class="col-md-12">
      <ul class="list-inline">
        <li><%= link_to t('export_to_csv'), 'javascript:;', class: 'md-trigger btn btn-info', data: { modal: 'export-to-csv-modal' } %></li>
      </ul>
      <br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t('payments') %></h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <table id="datatable" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th><%= t('first_name') %></th>
                    <th><%= t('last_name') %></th>
                    <th><%= t('paid') %></th>
                    <th><%= t('due_on') %></th>
                    <th><%= t('paid_on') %></th>
                  </tr>
                </thead>

                <tbody>
                  <% @payments.each do |payment| %>
                    <tr class="clickable-row" data-href="<%= payment_url(payment) %>">
                      <td><%= payment.user.first_name %></td>
                      <td><%= payment.user.last_name %></td>
                      <td><%= payment.paid? %></td>
                      <td><%= payment.due_on.in_time_zone(current_account.time_zone).strftime('%-m/%-d/%Y').strip %></td>
                      <td><%= payment.paid_on.try { |paid_on| paid_on.in_time_zone(current_account.time_zone).strftime('%-m/%-d/%Y').strip } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="md-modal md-effect-16" id="export-to-csv-modal">
  <%= form_tag export_payments_path(format: :csv), { onsubmit: "$('a.md-close')[0].click();", method: :get, class: 'form-horizontal' } do |f| %>
    <div class="md-content">
      <h3><%= t('export_to_csv') %></h3>

      <div class="form-group">
        <label class="control-label col-lg-2"><%= I18n.t('start_on') %></label>
        <div class="col-lg-10">
          <%= date_field_tag :start_date, Date.today - 30.days, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-lg-2"><%= I18n.t('end_on') %></label>
        <div class="col-lg-10">
          <%= date_field_tag :end_date, Date.today, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group m-b-0">
        <div class="col-sm-offset-4 col-sm-8">
          <%= link_to t('cancel'), 'javascript:;', class: 'md-close btn btn-default btn-sm' %>
          <%= submit_tag t('submit'), class: 'btn-sm btn-primary md-close' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="md-overlay"></div>

app/views/payments/show.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= t('invoice') %></h3>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="clearfix">
            <div class="pull-left">
              <h4 class="text-right"><%= current_account.name %></h4>
            </div>
            <div class="pull-right">
              <%= link_to t('edit'), edit_payment_path(@payment), class: 'btn btn-info' %>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-12">
              <% if current_account.address_available? %>
                <div class="pull-left m-t-30">
                  <address>
                    <strong><%= current_account.name %></strong><br>
                    <%= current_account.address %><br>
                    <% if current_account.address2.present? %>
                      <%= current_account.address2 %><br>
                    <% end %>
                    <%= current_account.city %>, <%= current_account.state %> <%= current_account.zip_code %><br>
                    <abbr title="Phone">P:</abbr> <%= current_account.phone %>
                  </address>
                </div>
              <% end %>
              <div class="pull-right m-t-30">
                <p><strong><%= t('date') %>: </strong> <%= @payment.created_at.to_date.to_formatted_s(:long) %></p>
                <p><strong><%= t('due_on') %>: </strong> <%= @payment.due_on.to_date.to_formatted_s(:long) %></p>
                <p class="m-t-10"><strong><%= t('payment_status') %>: </strong> <span class="label label-<%= @payment.paid? ? 'success' : 'warning' %>"><%= @payment.payment_status %></span></p>
              </div>
            </div>
          </div>
          <div class="m-h-50"></div>
          <div class="row">
            <div class="col-md-12">
              <div class="table-responsive">
                <table class="table m-t-30">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th><%= t('item') %></th>
                      <th><%= t('description') %></th>
                      <th><%= t('total') %></th>
                      <% if current_user.admin? && !@payment.paid? %>
                        <th><%= t('actions') %></th>
                      <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <% @payment_items.each_with_index do |payment_item, index| %>
                      <tr>
                        <td><%= index + 1 %></td>
                        <td><%= payment_item.itemable.class.name %></td>
                        <td><%= payment_item.itemable.class.name %></td>
                        <td><%= humanized_money_with_symbol(payment_item.itemable.payable_amount) %></td>
                        <% unless @payment.paid? %>
                          <td>
                            <%= link_to payment_item_path(payment_item) do %>
                              <span class="label bg-success inline m-t-10">Show</span>
                            <% end %>
                            <%= link_to payments_payment_item_path(payment_item), method: :delete do %>
                              <span class="label bg-danger inline m-t-10">Delete</span>
                            <% end %>
                          </td>
                        <% end %>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="row" style="border-radius: 0px;">
            <div class="col-md-3 col-md-offset-9">
              <p class="text-right"><b><%= t('subtotal') %>:</b> <%= humanized_money_with_symbol(@payment.subtotal) %></p>
              <p class="text-right"><%= t('discount') %>: <%= number_to_percentage(@payment.discount_to_number) %></p>
              <hr>
              <h3 class="text-right"><%= @payment.total.currency.to_s %> <%= humanized_money_with_symbol(@payment.total) %></h3>
            </div>
          </div>
          <hr>
          <div class="hidden-print">
            <div class="pull-right">
              <% if @payment.payable_by_student? %>
                <a href="#" class="btn btn-primary"><%= t('submit') %></a>
              <% else %>
                <%= link_to t('submit'), 'javascript:;', class: 'md-trigger btn btn-primary', data: { modal: 'modal-16' } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="md-modal md-effect-16" id="modal-16">
  <%= form_for @payment, html: { class: 'form-horizontal' } do |f| %>
    <div class="md-content">
      <h3><%= t('submit_payment') %></h3>
      <%= f.hidden_field :paid, value: true %>
      <%= f.hidden_field :paid_on, value: Time.zone.now %>
      <div class="form-group">
        <%= f.label :payment_method, class: 'col-sm-4 control-label' %>
        <div class="col-sm-8">
          <%= f.select :payment_method, Payment.payment_methods_collection, {}, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group m-b-0">
        <div class="col-sm-offset-4 col-sm-8">
          <%= link_to t('cancel'), 'javascript:;', class: 'md-close btn btn-default btn-sm' %>
          <%= f.submit t('submit'), class: 'btn-sm btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="md-overlay"></div>