config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'home#index'

  resources :accounts, only: [:show, :create, :update]

  resources :account_subscriptions, only: [:show, :update]

  resources :users do
    resources :todos
  end
  post '/users_create' => 'users#create'

  resources :inquired_users, only: [:index, :update]

  resources :available_days

  resources :levels do
    resources :level_memberships, only: [:create, :destroy, :update]
  end

  resources :pricing_plans do
    resources :plan_enrollments, only: [:new, :create, :destroy, :update]
  end

  resources :rooms

  resources :roles

  resources :users_roles, only: [:create, :destroy]

  resources :housings do
    resources :housing_occupancies, only: [:create, :destroy, :update]
  end

  resources :events do
    resources :event_sessions
    resources :event_attendances
  end

  resources :event_sessions do
    resources :event_attendances
  end

  resources :class_schedules

  resources :start_end_times

  resources :payments

  resources :payment_items

  namespace :payments do
    resources :payment_items, only: :destroy
  end
  get 'export_payments' => 'payments/csv_exporters#index', default: { format: :csv }

  resources :integrations

  resources :integration_processors, only: :create

  resources :report_teachers, only: :index

  resources :registration_forms, only: [:show, :update]

  namespace :registration_forms do
    resources :student_registrations, only: [:new, :create]
  end

  resources :terms_of_services

  resources :user_initial_setup, only: :index

  namespace :user_initial_setup do
    resources :assign_user_to_accounts, only: :create
  end

  # Integration sample files downloads routes
  get 'integration_user_csv' => 'integrations_sample_file_downloads#download_user_csv'
  get 'integration_housing_csv' => 'integrations_sample_file_downloads#download_housing_csv'
  get 'integration_housing_occupancy_csv' => 'integrations_sample_file_downloads#download_housing_occupancy_csv'
  get 'integration_plan_enrollment_csv' => 'integrations_sample_file_downloads#download_plan_enrollment_csv'

  namespace :ui, defaults: { format: 'json' } do
    namespace :v1 do
      resources :rooms, only: :index
      resources :students, only: :index
      resources :teachers, only: :index
      resources :class_sessions, only: %i(create show update destroy)
      resources :schedule_exports, only: :create

      resources :todos, only: %i(create index) do
        patch :update, on: :collection
      end
    end
  end

  # Stripe subscription actions
  post 'subscribe' => 'stripe_subscriptions#subscribe'
  post 'resume_subscription' => 'stripe_subscriptions#resume_subscription'
  post 'pause_subscription' => 'stripe_subscriptions#pause_subscription'
  post 'add_a_new_card' => 'stripe_subscriptions#add_a_new_card'
  delete 'delete_card' => 'stripe_subscriptions#delete_card'
  put 'make_default_card' => 'stripe_subscriptions#make_default_card'
end

app/models/event_session.rb
class EventSession < ApplicationRecord
  has_many :event_attendances, dependent: :destroy
  has_many :attendees, through: :event_attendances, source: :user
  has_one :start_end_time, as: :timeable, dependent: :destroy
  belongs_to :account
  belongs_to :event

  validates :account, presence: true
  validates :event, presence: true

  accepts_nested_attributes_for :start_end_time
end

app/controllers/event_sessions_controller.rb
class EventSessionsController < ApplicationController
  before_action :authenticate_user!, :find_event
  before_action :find_event_session, only: [:edit, :show, :update, :destroy]

  def new
    @event_session = @event.event_sessions.new(account: current_account)
    authorize @event_session
    @event_session.build_start_end_time
  end

  def edit
    authorize @event_session
  end

  def show
    authorize @event_session
  end

  def create
    @event_session = @event.event_sessions.new(event_session_params.merge(account: current_account))
    authorize @event_session
    @event_session.start_end_time.timeable = @event_session
    @event_session.start_end_time.account = current_account

    if @event_session.save
      flash[:success] = I18n.t('event_session_successfully_created')
      redirect_to event_event_session_path(@event, @event_session)
    else
      flash[:error] = I18n.t('something_went_wrong')
      render :new
    end
  end

  def update
    @event_session.assign_attributes(event_session_params)
    authorize @event_session
    @event_session.start_end_time.timeable = @event_session
    @event_session.start_end_time.account = current_account

    if @event_session.save
      flash[:success] = I18n.t('event_session_successfully_updated')
      redirect_to event_event_session_path(@event, @event_session)
    else
      flash[:error] = I18n.t('something_went_wrong')
      render :edit
    end
  end

  def destroy
    authorize @event_session
    @event_session.destroy
    flash[:success] = I18n.t('event_session_successfully_deleted')
    redirect_to @event
  end

  private

  def find_event
    @event = current_account.events.find(params[:event_id])
  end

  def find_event_session
    @event_session = @event.event_sessions.find(params[:id])
  end

  def event_session_params
    params.require(:event_session).permit(:maximum_capacity,
      start_end_time_attributes: [:id, :start_date, :start_time, :end_date, :end_time, :timeable_id, :timeable_type, :account_id])
  end
end

app/views/event_sessions/_form.html.erb
<%= form_for [event, event_session], html: { class: 'cmxform form-horizontal tasi-form' } do |f| %>
  <div class="form-group">
    <%= f.label :maximum_capacity, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :maximum_capacity, class: 'form-control' %>
    </div>
  </div>

  <%= render partial: 'start_end_times/fields_for_form', locals: { timeable: event_session, f: f } %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit t('save'), class: 'btn btn-success' %>
      <%= link_to t('cancel'), :back, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/event_sessions/edit.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= t('edit_event_session') %></h3>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @event.name %> - <%= t('session') %></h3>
        </div>
        <div class="panel-body">
          <div class="form">
            <%= render partial: 'form', locals: { event_session: @event_session, event: @event } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/event_sessions/new.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= t('new_event_session') %></h3>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t('new_event_session') %></h3>
        </div>
        <div class="panel-body">
          <div class="form">
            <%= render partial: 'form', locals: { event_session: @event_session, event: @event } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/event_sessions/show.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= link_to @event.name, event_path(@event) %> - <%= t('session') %></h3>
  </div>

  <div class="row">
    <div class="col-md-12">
      <ul class="list-inline">
        <li><%= link_to t('edit'), edit_event_event_session_path(@event, @event_session), class: 'btn btn-info'  %></li>
        <li><%= link_to t('delete'), event_event_session_path(@event, @event_session), method: :delete, class: 'btn btn-danger', data: { confirm: t('are_you_sure') } %></li>
      </ul>
      <br>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-sm-6 col-md-3">
      <div class="panel">
        <div class="h2 text-purple"><%= humanized_money_with_symbol @event.price %></div>
        <span class="text-muted"><%= t('price') %></span>
        <div class="text-right">
          <i class="fa fa-usd fa-2x text-purple"></i>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-3">
      <div class="panel bg-primary">
        <div class="h2 text-white"><%= @event_session.maximum_capacity %></div>
        <span class="text-white"><%= t('maximum_capacity') %></span>
        <div class="text-right">
          <i class="fa fa-university fa-2x text-white"></i>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-3">
      <div class="panel">
        <div class="h2 text-primary"><%= @event_session.attendees.count %></div>
        <span class="text-muted"><%= t('attendees') %></span>
        <div class="text-right">
          <i class="fa fa-users fa-2x text-primary"></i>
        </div>
      </div>
    </div>
  </div>

  <div class="page-title">
    <h3 class="title"><%= t('attendees') %></h3>
  </div>

  <div class="row">
    <div class="col-md-12">
      <ul class="list-inline">
        <li><%= link_to t('add_attendees'), 'javascript:;', class: 'md-trigger btn btn-info', data: { modal: 'new-event-session-modal' } %></li>
      </ul>
      <br>
    </div>
  </div>

  <% if @event_session.attendees.any? %>
    <div class="row">
      <div class="col-md-12">
        <div class="portlet">
          <div class="portlet-heading">
            <h3 class="portlet-title text-dark text-uppercase"><%= t('attendees') %></h3>
          </div>

          <div class="panel-collapse collapse in">
            <div class="portlet-body">
              <ul class="list-group list-group-lg">
                <% @event_session.attendees.each do |user| %>
                  <li class="list-group-item b-0">
                    <%= link_to user_path(user), class: 'm-r-10' do %>
                      <%= image_tag user.avatar.url(:thumb), class: 'thumb-sm br-radius' %>
                    <% end %>
                    <% event_attendance = EventAttendance.find_by(event_session: @event_session, user: user, account: current_account) %>
                    <%= link_to event_session_event_attendance_path(@event_session, event_attendance), method: :delete do %>
                      <span class="pull-right label bg-danger inline m-t-10"><%= t('delete') %></span>
                    <% end %>
                    <%= link_to user.full_name, user_path(user) %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="md-modal md-effect-16" id="new-event-session-modal">
  <%= form_for [@event_session, @event_session.event_attendances.build], html: { class: 'form-horizontal' } do |f| %>
    <div class="md-content">
      <h3><%= t('enroll_a_user') %></h3>

      <div class="form-group">
        <%= f.label :user_id, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.select :user_id, current_account.students_collection(@event_session.attendees), {}, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group m-b-0">
        <div class="col-sm-offset-4 col-sm-8">
          <%= link_to t('cancel'), 'javascript:;', class: 'md-close btn btn-default btn-sm' %>
          <%= f.submit t('submit'), class: 'btn-sm btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="md-overlay"></div>