config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'home#index'

  resources :accounts, only: [:show, :create, :update]

  resources :account_subscriptions, only: [:show, :update]

  resources :users do
    resources :todos
  end
  post '/users_create' => 'users#create'

  resources :inquired_users, only: [:index, :update]

  resources :available_days

  resources :levels do
    resources :level_memberships, only: [:create, :destroy, :update]
  end

  resources :pricing_plans do
    resources :plan_enrollments, only: [:new, :create, :destroy, :update]
  end

  resources :rooms

  resources :roles

  resources :users_roles, only: [:create, :destroy]

  resources :housings do
    resources :housing_occupancies, only: [:create, :destroy, :update]
  end

  resources :events do
    resources :event_sessions
    resources :event_attendances
  end

  resources :event_sessions do
    resources :event_attendances
  end

  resources :class_schedules

  resources :start_end_times

  resources :payments

  resources :payment_items

  namespace :payments do
    resources :payment_items, only: :destroy
  end
  get 'export_payments' => 'payments/csv_exporters#index', default: { format: :csv }

  resources :integrations

  resources :integration_processors, only: :create

  resources :report_teachers, only: :index

  resources :registration_forms, only: [:show, :update]

  namespace :registration_forms do
    resources :student_registrations, only: [:new, :create]
  end

  resources :terms_of_services

  resources :user_initial_setup, only: :index

  namespace :user_initial_setup do
    resources :assign_user_to_accounts, only: :create
  end

  # Integration sample files downloads routes
  get 'integration_user_csv' => 'integrations_sample_file_downloads#download_user_csv'
  get 'integration_housing_csv' => 'integrations_sample_file_downloads#download_housing_csv'
  get 'integration_housing_occupancy_csv' => 'integrations_sample_file_downloads#download_housing_occupancy_csv'
  get 'integration_plan_enrollment_csv' => 'integrations_sample_file_downloads#download_plan_enrollment_csv'

  namespace :ui, defaults: { format: 'json' } do
    namespace :v1 do
      resources :rooms, only: :index
      resources :students, only: :index
      resources :teachers, only: :index
      resources :class_sessions, only: %i(create show update destroy)
      resources :schedule_exports, only: :create

      resources :todos, only: %i(create index) do
        patch :update, on: :collection
      end
    end
  end

  # Stripe subscription actions
  post 'subscribe' => 'stripe_subscriptions#subscribe'
  post 'resume_subscription' => 'stripe_subscriptions#resume_subscription'
  post 'pause_subscription' => 'stripe_subscriptions#pause_subscription'
  post 'add_a_new_card' => 'stripe_subscriptions#add_a_new_card'
  delete 'delete_card' => 'stripe_subscriptions#delete_card'
  put 'make_default_card' => 'stripe_subscriptions#make_default_card'
end

app/models/terms_of_service.rb
class TermsOfService < ApplicationRecord
  belongs_to :account
  has_many :terms_of_service_acceptances, dependent: :destroy
  has_many :users, through: :terms_of_service_acceptances

  validates :account, presence: true
  validates :name, presence: true
  validates :body, presence: true

  before_save :invalidate_defaults, if: :default?

  private

  def invalidate_defaults
    account.terms_of_services.update_all(default: false)
  end
end

app/controllers/terms_of_services_controller.rb
class TermsOfServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_terms_of_service, only: [:show, :edit, :update, :destroy]

  def index
    @terms_of_services = policy_scope(TermsOfService)
  end

  def new
    @terms_of_service = current_account.terms_of_services.new
    authorize @terms_of_service
  end

  def show
    authorize @terms_of_service
  end

  def edit
    authorize @terms_of_service
  end

  def create
    @terms_of_service = current_account.terms_of_services.new(terms_of_service_params)

    if @terms_of_service.save
      flash[:success] = I18n.t('terms_of_service_successfully_created')
      redirect_to @terms_of_service
    else
      flash[:error] = I18n.t('something_went_wrong')
      render :new
    end
  end

  def update
    if @terms_of_service.update_attributes(terms_of_service_params)
      flash[:success] = I18n.t('terms_of_service_successfully_updated')
      redirect_to @terms_of_service
    else
      flash[:error] = I18n.t('something_went_wrong')
      render :edit
    end
  end

  def destroy
    authorize @terms_of_service
    @terms_of_service.destroy
    redirect_to terms_of_services_path
  end

  private

  def find_terms_of_service
    @terms_of_service = current_account.terms_of_services.find(params[:id])
  end

  def terms_of_service_params
    params.require(:terms_of_service).permit(:name, :body, :default)
  end
end

app/views/terms_of_services/_form.html.erb
<%= form_for terms_of_service, html: { class: 'cmxform form-horizontal tasi-form' } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :body, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :default, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :default, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit t('save'), class: 'btn btn-success' %>
      <%= link_to t('cancel'), :back, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/terms_of_services/edit.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= t('edit_terms_of_services') %></h3>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t('edit_terms_of_services') %></h3>
        </div>
        <div class="panel-body">
          <div class="form">
            <%= render partial: 'form', locals: { terms_of_service: @terms_of_service } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/terms_of_services/index.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= t('terms_of_services') %></h3>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t('terms_of_services') %></h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <table id="datatable" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th><%= t('name') %></th>
                    <th><%= t('number_of_students') %></th>
                    <th><%= t('default') %></th>
                  </tr>
                </thead>

                <tbody>
                  <% @terms_of_services.each do |terms_of_service| %>
                    <tr class="clickable-row" data-href="<%= terms_of_service_url(terms_of_service) %>">
                      <td><%= terms_of_service.name %></td>
                      <td><%= terms_of_service.users.uniq.count %></td>
                      <td><%= terms_of_service.default? %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/terms_of_services/new.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= t('new_terms_of_service') %></h3>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t('new_terms_of_service') %></h3>
        </div>
        <div class="panel-body">
          <div class="form">
            <%= render partial: 'form', locals: { terms_of_service: @terms_of_service } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/terms_of_services/show.html.erb
<div class="wraper container-fluid">
  <div class="page-title">
    <h3 class="title"><%= @terms_of_service.name %></h3>
  </div>

  <div class="row">
    <div class="col-md-12">
      <ul class="list-inline">
        <li><%= link_to t('edit'), edit_terms_of_service_path(@terms_of_service), class: 'btn btn-info'  %></li>
        <li><%= link_to t('delete'), terms_of_service_path(@terms_of_service), method: :delete, class: 'btn btn-danger', data: { confirm: t('are_you_sure') } %></li>
      </ul>
      <br>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-sm-6 col-md-3">
      <div class="panel">
        <div class="h2 text-primary"><%= @terms_of_service.users.uniq.count %></div>
        <span class="text-muted"><%= t('accepted_users_count') %></span>
        <div class="text-right">
          <i class="fa fa-user fa-2x text-primary"></i>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-8"></div>
  </div>

  <div class="page-title">
    <h3 class="title"><%= t('occupants') %></h3>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="portlet">
        <div class="portlet-heading">
          <h3 class="portlet-title text-dark text-uppercase"><%= t('remove_users_from_role') %></h3>
        </div>

        <div class="panel-collapse collapse in">
          <div class="portlet-body">
            <ul class="list-group list-group-lg">
              <% @terms_of_service.users.each do |user| %>
                <li class="list-group-item b-0">
                  <%= link_to user_path(user), class: 'm-r-10' do %>
                    <%= image_tag user.avatar.url(:thumb), class: 'thumb-sm br-radius' %>
                  <% end %>
                  <%= link_to user.full_name, user_path(user) %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>